# Tag release and update changelog
name: Tag release and update Changelog

on:
  workflow_dispatch:
    inputs:
      release-sha:
        required: true
        type: string

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        # Updates changelog and writes the release version into the environment
        - name: Update Changelog
          run: python3 tools/maint/create_release.py --action
        - name: Create Changelog PR
          id: cpr
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.EMSCRIPTEN_BOT_TOKEN }}
            title: Mark ${{ env.RELEASE_VERSION }} as released
            team-reviewers: release-reviewers
            delete-branch: true
        - name: Enable auto-merge
          run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
          env:
            GH_TOKEN: ${{ secrets.EMSCRIPTEN_BOT_TOKEN }}
