# Tag release and update changelog
name: Tag release and update Changelog

on:
  workflow_dispatch:
    inputs:
      release-sha:
        required: true
        type: string
  push:

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        - name: Tag release sha
          uses: actions/github-script@v7
          with:
            script: |
              console.log('running');
