# Tag release and update changelog
name: Tag release and update Changelog

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
      release-sha:
        required: true
        type: string

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        - name: Tag release sha
          uses: actions/github-script@v7
          with:
            script: |
              console.log('running');
              const tag_sha = '${{ inputs.release-sha }}';
              const release_version = '${{ inputs.release-version }}';
              console.log(`Version ${release_version} at SHA ${tag_sha}`);
              const regex = /^[0-9]+.[0-9]+.[0-9]+$/;
              const match = release_version.match(regex);
              if (!match) {
                throw new Error('Malformed release version');
              }
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${release_version}`,
                sha: tag_sha
              });
